### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Oops-re** [FBLeee/IDA_ChatGpt#1]
师傅，gepetto-locales文件夹中的文件是干嘛的呀？想在脚本添加一些新的接口

**Comment by FBLeee** [comment]
> 师傅，gepetto-locales文件夹中的文件是干嘛的呀？想在脚本添加一些新的接口

你好，这个主要是用来翻译的组件，
 Specify the program language. It can be "fr_FR", "zh_CN", or any folder in gepetto-locales.
 Defaults to English.
